// Mock data for fallback when MongoDB is unavailable
export const mockSchemes = [
  {
    _id: '1',
    title: 'PM Kisan Samman Nidhi',
    description: 'Direct income support of ₹6,000 per year to farmer families, payable in three equal installments of ₹2,000 each.',
    organization: 'Ministry of Agriculture',
    category: 'agriculture',
    state: 'all-india',
    eligibility: 'Small and marginal farmers',
    benefitAmount: '₹6,000/year',
    lastDate: '2024-12-31',
    isActive: true,
  },
  {
    _id: '2',
    title: 'Ayushman Bharat Yojana',
    description: 'Health insurance coverage of up to ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
    organization: 'Ministry of Health',
    category: 'healthcare',
    state: 'all-india',
    eligibility: 'Economically weaker sections',
    benefitAmount: '₹5 lakh cover',
    lastDate: '2024-12-31',
    isActive: true,
  },
  {
    _id: '3',
    title: 'Pradhan Mantri Awas Yojana',
    description: 'Housing for All scheme providing affordable housing with interest subsidy on home loans.',
    organization: 'Ministry of Housing',
    category: 'housing',
    state: 'all-india',
    eligibility: 'LIG/EWS households',
    benefitAmount: 'Up to ₹2.67 lakh subsidy',
    lastDate: '2025-03-31',
    isActive: true,
  },
  {
    _id: '4',
    title: 'Start-up India Seed Fund',
    description: 'Financial assistance to startups for proof of concept, prototype development, product trials, and market entry.',
    organization: 'DPIIT',
    category: 'business',
    state: 'all-india',
    eligibility: 'Recognized startups',
    benefitAmount: 'Up to ₹1 Crore',
    lastDate: '2024-11-30',
    isActive: true,
  },
  {
    _id: '5',
    title: 'Mudra Loan Yojana',
    description: 'Loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises for income-generating activities.',
    organization: 'Ministry of Finance',
    category: 'finance',
    state: 'all-india',
    eligibility: 'Small business owners',
    benefitAmount: '₹50K - ₹10 Lakh',
    lastDate: '2024-12-31',
    isActive: true,
  },
  {
    _id: '6',
    title: 'Skill India Mission (PMKVY)',
    description: 'Free skill training and certification for youth in various sectors to enhance employability.',
    organization: 'Ministry of Skill Development',
    category: 'education',
    state: 'all-india',
    eligibility: 'Youth 18-35 years',
    benefitAmount: 'Free training + stipend',
    lastDate: '2024-12-31',
    isActive: true,
  },
]

export const mockExams = [
  {
    _id: '1',
    title: 'UPSC Civil Services Examination',
    description: 'Preliminary, Main Examination, and Personality Test for recruitment to All India Services and Central Services.',
    organization: 'UPSC',
    examType: 'civil-services',
    state: 'all-india',
    eligibility: 'Graduate, Age 21-32',
    applicationStart: '2024-02-14',
    applicationEnd: '2024-03-05',
    examDate: '2024-05-26',
    posts: 1056,
    isActive: true,
  },
  {
    _id: '2',
    title: 'SSC CGL Examination',
    description: 'Combined Graduate Level examination for Group B and C posts in various ministries and departments.',
    organization: 'SSC',
    examType: 'staff-selection',
    state: 'all-india',
    eligibility: 'Graduate, Age 18-32',
    applicationStart: '2024-06-11',
    applicationEnd: '2024-07-10',
    examDate: '2024-09-15',
    posts: 7500,
    isActive: true,
  },
  {
    _id: '3',
    title: 'IBPS PO Examination',
    description: 'Probationary Officer recruitment in public sector banks through Common Recruitment Process.',
    organization: 'IBPS',
    examType: 'banking',
    state: 'all-india',
    eligibility: 'Graduate, Age 20-30',
    applicationStart: '2024-07-01',
    applicationEnd: '2024-07-21',
    examDate: '2024-10-19',
    posts: 4332,
    isActive: true,
  },
  {
    _id: '4',
    title: 'NEET UG',
    description: 'National Eligibility cum Entrance Test for admission to undergraduate medical courses in India.',
    organization: 'NTA',
    examType: 'medical',
    state: 'all-india',
    eligibility: '12th with PCB, Age 17+',
    applicationStart: '2024-02-09',
    applicationEnd: '2024-03-09',
    examDate: '2024-05-05',
    posts: null,
    isActive: true,
  },
  {
    _id: '5',
    title: 'JEE Main',
    description: 'Joint Entrance Examination for admission to NITs, IIITs, and other centrally funded institutions.',
    organization: 'NTA',
    examType: 'engineering',
    state: 'all-india',
    eligibility: '12th with PCM',
    applicationStart: '2024-11-01',
    applicationEnd: '2024-11-30',
    examDate: '2025-01-24',
    posts: null,
    isActive: true,
  },
  {
    _id: '6',
    title: 'Railway RRB NTPC',
    description: 'Non-Technical Popular Categories recruitment for various posts in Indian Railways.',
    organization: 'RRB',
    examType: 'railway',
    state: 'all-india',
    eligibility: '12th/Graduate, Age 18-33',
    applicationStart: '2024-08-10',
    applicationEnd: '2024-09-09',
    examDate: '2024-12-15',
    posts: 35000,
    isActive: true,
  },
]

export const mockJobs = [
  {
    _id: '1',
    title: 'Indian Administrative Service (IAS)',
    description: 'Premier administrative civil service of the Government of India. Officers handle administration of various government affairs.',
    organization: 'Government of India',
    department: 'Cabinet Secretariat',
    jobType: 'central-govt',
    state: 'all-india',
    eligibility: 'Graduate, Age 21-32, UPSC qualified',
    salary: '₹56,100 - ₹2,50,000',
    posts: 180,
    applicationEnd: '2025-03-05',
    isActive: true,
  },
  {
    _id: '2',
    title: 'Bank Probationary Officer (SBI PO)',
    description: 'Management trainee role leading to Assistant Manager in State Bank of India branches across India.',
    organization: 'State Bank of India',
    department: 'Banking',
    jobType: 'banking',
    state: 'all-india',
    eligibility: 'Graduate, Age 21-30',
    salary: '₹36,000 - ₹63,000',
    posts: 2000,
    applicationEnd: '2024-09-15',
    isActive: true,
  },
  {
    _id: '3',
    title: 'SSC CHSL Data Entry Operator',
    description: 'Lower Division Clerk and Data Entry Operator positions in various central government departments.',
    organization: 'SSC',
    department: 'Various Ministries',
    jobType: 'central-govt',
    state: 'all-india',
    eligibility: '12th Pass, Age 18-27',
    salary: '₹19,900 - ₹63,200',
    posts: 5000,
    applicationEnd: '2024-08-20',
    isActive: true,
  },
  {
    _id: '4',
    title: 'Indian Railways Assistant Loco Pilot',
    description: 'Operate and maintain locomotives, ensure safe and timely train operations across railway zones.',
    organization: 'Indian Railways',
    department: 'RRB',
    jobType: 'railway',
    state: 'all-india',
    eligibility: 'ITI/Diploma, Age 18-30',
    salary: '₹19,900 - ₹34,800',
    posts: 24000,
    applicationEnd: '2024-10-30',
    isActive: true,
  },
  {
    _id: '5',
    title: 'Income Tax Inspector',
    description: 'Handle assessment, collection, and enforcement of direct taxes in the Income Tax Department.',
    organization: 'CBDT',
    department: 'Ministry of Finance',
    jobType: 'central-govt',
    state: 'all-india',
    eligibility: 'Graduate, Age 18-30, SSC CGL',
    salary: '₹44,900 - ₹1,42,400',
    posts: 1200,
    applicationEnd: '2024-11-15',
    isActive: true,
  },
  {
    _id: '6',
    title: 'DRDO Scientist B',
    description: 'Research and development positions in Defence Research and Development Organisation laboratories.',
    organization: 'DRDO',
    department: 'Ministry of Defence',
    jobType: 'defence',
    state: 'all-india',
    eligibility: 'B.Tech/M.Sc, Age 28',
    salary: '₹56,100 - ₹1,77,500',
    posts: 630,
    applicationEnd: '2024-12-10',
    isActive: true,
  },
]
